#Secret: Stores sensitive data (passwords) in Kubernetes
#stringData: Allows plain text, Kubernetes automatically base64 encodes it
#Multiple passwords: One for PostgreSQL admin, one for Keycloak user
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: keycloak
type: Opaque
stringData:  # Using stringData so we can write plain text (Kubernetes will encode it)
  postgres-password: "ChangeThisSecurePassword123!"
  postgres-user: "postgres"
  keycloak-password: "1234"
  keycloak-user: "keycloak"
  keycloak-db: "keycloak"
