#ConfigMap: Stores non-sensitive configuration
#POSTGRES_DB: Default database name
#Performance settings: Optimizes PostgreSQL for Keycloak
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: keycloak
data:
  POSTGRES_DB: "keycloak"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  # PostgreSQL performance tuning
  shared_buffers: "256MB"
  effective_cache_size: "1GB"
  maintenance_work_mem: "64MB"
  checkpoint_completion_target: "0.9"
  wal_buffers: "16MB"
  default_statistics_target: "100"
